### ISSUE TITLE
API changes in PyCharm 2017.3

### ISSUE THREAD

**Issue by sproshev** [jhominal/pysynthetic-intellij#2]
We've changed `com.jetbrains.python.psi.PyFunction` and `com.jetbrains.python.psi.impl.stubs.PyNamedParameterStubImpl` in PyCharm 2017.3.

Now there are two compatibility problems:

`Abstract method com.jetbrains.python.psi.PyFunction.onlyRaisesNotImplementedError() : boolean is not implemented`

and

`Invocation of unresolved method com.jetbrains.python.psi.impl.stubs.PyNamedParameterStubImpl.<init>(String, boolean, boolean, boolean, String, StubElement, IStubElementType)`.

Could you please fix them? Sorry for inconvenience.

**Comment by jhominal** [comment]
Hello,

Thank you for the report.

I had seen the report when you posted it, and I thought I would have time to handle it right away... But I have not done that yet.

I hope to do that soon, by releasing a new version.

**Comment by jhominal** [comment]
This issue should be fixed by [release v0.6.0](releases/v0.6.0)

**Comment by jhominal** [comment]
And again, thank you @sproshev for your report, that is appreciated.

**Comment by sproshev** [comment]
Thank you for update!
