### ISSUE TITLE
API changes in PyCharm 2018.2

### ISSUE THREAD

**Issue by sproshev** [jhominal/pysynthetic-intellij#4]
Hello!

We've changed `com.jetbrains.python.psi.impl.stubs.PyNamedParameterStubImpl` so that one of its constructor is marked to be removed in 2018.2. As I can see this constructor is used in `SyntheticInitParameter` and `VirtualParameter` classes.

Could you please fix? Sorry for inconvenience!

**Comment by jhominal** [comment]
Hello,

Thank you for reporting.

From what I can see, I am already using the right constructor overload for that class (it has 8 parameters, while the one that is going to be removed, according to [PyNamedParameterSubImpl.java](https://github.com/JetBrains/intellij-community/blob/182.2574/python/src/com/jetbrains/python/psi/impl/stubs/PyNamedParameterStubImpl.java), has only 7 parameters.)

See [SyntheticInitParameter.java line 29](https://github.com/jhominal/pysynthetic-intellij/blob/6a01da27cf1bf09f9e5dd81dafe34c75f471c919/src/com/wishtack/pysynthetic/psi/SyntheticInitParameter.java#L29)
```java
return new PyNamedParameterStubImpl(syntheticMemberInfo.getName(), false, false, defaultValueText,null, null, null, PyElementTypes.NAMED_PARAMETER);
```

And [VirtualParameter.java line 20](https://github.com/jhominal/pysynthetic-intellij/blob/6a01da27cf1bf09f9e5dd81dafe34c75f471c919/src/com/wishtack/pysynthetic/psi/VirtualParameter.java#L20)

```java
super(new PyNamedParameterStubImpl(name, false, false, null, null, null, null, PyElementTypes.NAMED_PARAMETER));
```

As such, I do not think there is an issue. Can you confirm, @sproshev 

In any case, thank you for the report!

**Comment by sproshev** [comment]
@jhominal Confirmed, sorry :(
